[package]
name = "rlp"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.9.0"
hex-literal = "0.4.1"
criterion = "0.5.1"

[[bench]]
name="memcpy"
harness = false
path = "src/benches/memcpy.rs"